/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksPeriodRouteImport } from './routes/tasks.$period'
import { Route as StatsTasksRouteImport } from './routes/stats.tasks'
import { Route as FormsFormIdRouteImport } from './routes/forms.$formId'
import { Route as RecordsFormFormIdRouteImport } from './routes/records.form.$formId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksPeriodRoute = TasksPeriodRouteImport.update({
  id: '/tasks/$period',
  path: '/tasks/$period',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsTasksRoute = StatsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => StatsRoute,
} as any)
const FormsFormIdRoute = FormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsFormFormIdRoute = RecordsFormFormIdRouteImport.update({
  id: '/form/$formId',
  path: '/form/$formId',
  getParentRoute: () => RecordsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/records': typeof RecordsRouteWithChildren
  '/stats': typeof StatsRouteWithChildren
  '/forms/$formId': typeof FormsFormIdRoute
  '/stats/tasks': typeof StatsTasksRoute
  '/tasks/$period': typeof TasksPeriodRoute
  '/records/form/$formId': typeof RecordsFormFormIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/records': typeof RecordsRouteWithChildren
  '/stats': typeof StatsRouteWithChildren
  '/forms/$formId': typeof FormsFormIdRoute
  '/stats/tasks': typeof StatsTasksRoute
  '/tasks/$period': typeof TasksPeriodRoute
  '/records/form/$formId': typeof RecordsFormFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/records': typeof RecordsRouteWithChildren
  '/stats': typeof StatsRouteWithChildren
  '/forms/$formId': typeof FormsFormIdRoute
  '/stats/tasks': typeof StatsTasksRoute
  '/tasks/$period': typeof TasksPeriodRoute
  '/records/form/$formId': typeof RecordsFormFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/records'
    | '/stats'
    | '/forms/$formId'
    | '/stats/tasks'
    | '/tasks/$period'
    | '/records/form/$formId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/records'
    | '/stats'
    | '/forms/$formId'
    | '/stats/tasks'
    | '/tasks/$period'
    | '/records/form/$formId'
  id:
    | '__root__'
    | '/'
    | '/records'
    | '/stats'
    | '/forms/$formId'
    | '/stats/tasks'
    | '/tasks/$period'
    | '/records/form/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecordsRoute: typeof RecordsRouteWithChildren
  StatsRoute: typeof StatsRouteWithChildren
  FormsFormIdRoute: typeof FormsFormIdRoute
  TasksPeriodRoute: typeof TasksPeriodRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$period': {
      id: '/tasks/$period'
      path: '/tasks/$period'
      fullPath: '/tasks/$period'
      preLoaderRoute: typeof TasksPeriodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/tasks': {
      id: '/stats/tasks'
      path: '/tasks'
      fullPath: '/stats/tasks'
      preLoaderRoute: typeof StatsTasksRouteImport
      parentRoute: typeof StatsRoute
    }
    '/forms/$formId': {
      id: '/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof FormsFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/form/$formId': {
      id: '/records/form/$formId'
      path: '/form/$formId'
      fullPath: '/records/form/$formId'
      preLoaderRoute: typeof RecordsFormFormIdRouteImport
      parentRoute: typeof RecordsRoute
    }
  }
}

interface RecordsRouteChildren {
  RecordsFormFormIdRoute: typeof RecordsFormFormIdRoute
}

const RecordsRouteChildren: RecordsRouteChildren = {
  RecordsFormFormIdRoute: RecordsFormFormIdRoute,
}

const RecordsRouteWithChildren =
  RecordsRoute._addFileChildren(RecordsRouteChildren)

interface StatsRouteChildren {
  StatsTasksRoute: typeof StatsTasksRoute
}

const StatsRouteChildren: StatsRouteChildren = {
  StatsTasksRoute: StatsTasksRoute,
}

const StatsRouteWithChildren = StatsRoute._addFileChildren(StatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecordsRoute: RecordsRouteWithChildren,
  StatsRoute: StatsRouteWithChildren,
  FormsFormIdRoute: FormsFormIdRoute,
  TasksPeriodRoute: TasksPeriodRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
